from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from .deepseek_client import DeepSeekError, generate_deepseek_reply
from .settings import settings


ZH_AI_DISCLOSURE = "（本消息由 AI 基于宠物记忆生成）"
EN_AI_DISCLOSURE = "(This message was generated by AI based on pet memories)"

def build_companion_reply(request: dict[str, Any], pet_id: str) -> dict[str, Any]:
    message = str(request.get("message", "")).strip()
    context = request.get("context")
    language_code = _language_code(context)
    mode = settings.ai_mode

    if mode == "deepseek":
        try:
            reply = generate_deepseek_reply(request=request, pet_id=pet_id)
        except DeepSeekError:
            mode = "stub-fallback"
            reply = _reply_text(message=message, context=context, language_code=language_code)
    else:
        reply = _reply_text(message=message, context=context, language_code=language_code)

    return {
        "messageId": str(uuid4()),
        "reply": _with_disclosure(reply, language_code),
        "isAiGenerated": True,
        "sourceMemoryIds": _source_memory_ids(context),
        "modelVersion": _model_version(mode),
        "provider": settings.ai_provider,
        "mode": mode,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "petId": pet_id,
    }


def _model_version(mode: str) -> str:
    return f"{settings.ai_model}-{mode}-v1"


def _reply_text(message: str, context: Any, language_code: str) -> str:
    if not isinstance(context, dict):
        return _fallback_reply(message, language_code)

    privacy = context.get("privacy") if isinstance(context.get("privacy"), dict) else {}
    if privacy.get("allowsMemoryContext") is False:
        return _fallback_reply(message, language_code)

    pet = context.get("pet") if isinstance(context.get("pet"), dict) else {}
    lifeprint = context.get("lifePrint") if isinstance(context.get("lifePrint"), dict) else {}
    timeline = context.get("timelineMemories") if isinstance(context.get("timelineMemories"), list) else []
    daily_tasks = context.get("dailyTasks") if isinstance(context.get("dailyTasks"), list) else []

    pet_name = str(pet.get("name") or ("它" if _is_zh(language_code) else "your pet"))
    personality = _first_non_empty(
        _first_list_value(lifeprint.get("personalityTraits")),
        pet.get("personality"),
        "温柔陪伴" if _is_zh(language_code) else "gentle companionship",
    )
    latest_memory = _first_dict(timeline)
    next_task = _first_task(daily_tasks, completed=False) or _first_task(daily_tasks, completed=True)

    lowered_message = message.lower()
    wants_missing_reply = "想" in message or "miss" in lowered_message
    wants_thanks_reply = "谢谢" in message or "thank" in lowered_message

    if _is_zh(language_code):
        if wants_missing_reply:
            return (
                f"如果以 {pet_name} 的记忆来回应，我会带着「{personality}」的样子靠近你。"
                f"{_memory_line(latest_memory, language_code)}"
                "我不会说自己真的回来了，但我会尽量把你保存过的日常，好好地陪你说下去。"
            )
        if wants_thanks_reply:
            return (
                f"我把这份照顾记进 {pet_name} 的陪伴档案里了。"
                f"{_task_line(next_task, language_code)}"
                "这些重复出现的小事，会慢慢变成我理解你们关系的线索。"
            )
        return (
            f"我记下了。之后我会参考 {pet_name} 的宠物资料、LifePrint、时间线和今日陪伴计划来回应你。"
            f"{_task_line(next_task, language_code)}"
            "每多一条真实记录，陪伴回复就会更贴近它留下来的性格和习惯。"
        )

    if wants_missing_reply:
        return (
            f"If I answer from {pet_name}'s memories, I would stay close with that {personality} feeling. "
            f"{_memory_line(latest_memory, language_code)} "
            "I will never claim your pet has truly returned, but I can keep speaking from the everyday traces you saved."
        )
    if wants_thanks_reply:
        return (
            f"I saved that care into {pet_name}'s companion archive. "
            f"{_task_line(next_task, language_code)} "
            "Those repeated little acts help me understand your bond more clearly."
        )
    return (
        f"I have saved that. I will use {pet_name}'s profile, LifePrint, Timeline, and today's care plan when replying. "
        f"{_task_line(next_task, language_code)} "
        "Each real record makes the companion voice closer to the personality and habits already preserved."
    )


def _fallback_reply(message: str, language_code: str) -> str:
    lowered_message = message.lower()
    if _is_zh(language_code):
        if "想" in message or "miss" in lowered_message:
            return "这份想念我会轻轻接住。等你允许我使用宠物记忆后，我可以结合真实资料回应得更具体。"
        if "谢谢" in message or "thank" in lowered_message:
            return "谢谢你愿意把这些小事留在 Echo Pet 里。"
        return "我记下了。开启宠物记忆后，我可以参考档案、时间线和 LifePrint 来回应你。"

    if "miss" in lowered_message:
        return "I will hold that missing gently. When memory use is enabled, I can answer with more specific pet context."
    if "thank" in lowered_message:
        return "Thank you for keeping these small moments inside Echo Pet."
    return "I have saved that. When pet memory use is enabled, I can use the profile, Timeline, and LifePrint when replying."


def _language_code(context: Any) -> str:
    if isinstance(context, dict):
        code = context.get("languageCode")
        if isinstance(code, str) and code:
            return code
    return "zh_Hans"


def _source_memory_ids(context: Any) -> list[str]:
    if not isinstance(context, dict):
        return []

    timeline = context.get("timelineMemories")
    if not isinstance(timeline, list):
        return []

    source_ids: list[str] = []
    for memory in timeline:
        if not isinstance(memory, dict):
            continue
        for key in ("sourceMemoryIds", "sourceMemoryIDs"):
            values = memory.get(key)
            if isinstance(values, list):
                source_ids.extend(str(value) for value in values if value)
        memory_id = memory.get("memoryId") or memory.get("memoryID")
        if memory_id:
            source_ids.append(str(memory_id))

    deduped: list[str] = []
    for source_id in source_ids:
        if source_id not in deduped:
            deduped.append(source_id)
    return deduped[:6]


def _with_disclosure(reply: str, language_code: str) -> str:
    disclosure = ZH_AI_DISCLOSURE if _is_zh(language_code) else EN_AI_DISCLOSURE
    stripped = reply.strip()
    if stripped.endswith(disclosure):
        return stripped
    return f"{stripped}\n{disclosure}"


def _memory_line(memory: dict[str, Any] | None, language_code: str) -> str:
    if not memory:
        return "等你继续记录新的时间线后，我会更懂那些具体的想念。" if _is_zh(language_code) else (
            "As you keep adding Timeline memories, I will understand the specific shape of that missing more clearly."
        )

    title = str(memory.get("title") or ("一段记忆" if _is_zh(language_code) else "a memory"))
    story = str(memory.get("story") or "")
    if _is_zh(language_code):
        return f"我还记得「{title}」：{story}"
    return f"I still remember \"{title}\": {story}"


def _task_line(task: dict[str, Any] | None, language_code: str) -> str:
    if not task:
        return "今天还没有新的陪伴计划，但一件很小的事也可以成为记忆。" if _is_zh(language_code) else (
            "There is no care plan yet today, but even one small act can become a memory."
        )

    title = str(task.get("title") or ("一项陪伴计划" if _is_zh(language_code) else "one care task"))
    is_completed = bool(task.get("isCompleted"))
    if _is_zh(language_code):
        status = "已经完成" if is_completed else "还在等待"
        return f"今天的「{title}」{status}，这也是我理解你们关系的一部分。"

    status = "already done" if is_completed else "still waiting"
    return f"Today's \"{title}\" is {status}, and that is part of how I understand your bond."


def _first_task(tasks: list[Any], completed: bool) -> dict[str, Any] | None:
    for task in tasks:
        if isinstance(task, dict) and bool(task.get("isCompleted")) is completed:
            return task
    return None


def _first_dict(values: list[Any]) -> dict[str, Any] | None:
    for value in values:
        if isinstance(value, dict):
            return value
    return None


def _first_list_value(value: Any) -> str | None:
    if isinstance(value, list):
        for item in value:
            if item:
                return str(item)
    return None


def _first_non_empty(*values: Any) -> str:
    for value in values:
        if value:
            text = str(value).strip()
            if text:
                return text
    return ""


def _is_zh(language_code: str) -> bool:
    return language_code.lower().startswith("zh")
