from __future__ import annotations

import json
import ssl
import urllib.error
import urllib.request
from typing import Any, Callable

from .settings import settings

try:
    import certifi
except ImportError:  # pragma: no cover - production dependency, graceful local fallback.
    certifi = None


DeepSeekTransport = Callable[[dict[str, Any], dict[str, str], float], dict[str, Any]]


class DeepSeekError(RuntimeError):
    pass


class DeepSeekConfigurationError(DeepSeekError):
    pass


class DeepSeekClient:
    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.deepseek.com",
        model: str = "deepseek-v4-flash",
        timeout_seconds: float = 20,
        transport: DeepSeekTransport | None = None,
    ) -> None:
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout_seconds = timeout_seconds
        self.transport = transport

    def chat(self, messages: list[dict[str, str]]) -> str:
        if not self.api_key:
            raise DeepSeekConfigurationError("DEEPSEEK_API_KEY is required when ECHOPET_AI_MODE=deepseek.")

        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": 0.7,
            "max_tokens": 700,
            "thinking": {"type": "disabled"},
            "stream": False,
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        data = self.transport(payload, headers, self.timeout_seconds) if self.transport else self._post(payload, headers)
        return _extract_reply(data)

    def _post(self, payload: dict[str, Any], headers: dict[str, str]) -> dict[str, Any]:
        request = urllib.request.Request(
            f"{self.base_url}/chat/completions",
            data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_seconds, context=_ssl_context()) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            details = exc.read().decode("utf-8", errors="replace")
            raise DeepSeekError(f"DeepSeek HTTP {exc.code}: {details[:500]}") from exc
        except urllib.error.URLError as exc:
            raise DeepSeekError(f"DeepSeek request failed: {exc.reason}") from exc
        except json.JSONDecodeError as exc:
            raise DeepSeekError("DeepSeek response was not valid JSON.") from exc


def _ssl_context() -> ssl.SSLContext:
    if certifi is not None:
        return ssl.create_default_context(cafile=certifi.where())
    return ssl.create_default_context()


def generate_deepseek_reply(request: dict[str, Any], pet_id: str) -> str:
    client = DeepSeekClient(
        api_key=settings.deepseek_api_key,
        base_url=settings.deepseek_base_url,
        model=settings.ai_model,
        timeout_seconds=settings.ai_timeout_seconds,
    )
    return client.chat(build_deepseek_messages(request=request, pet_id=pet_id))


def build_deepseek_messages(request: dict[str, Any], pet_id: str) -> list[dict[str, str]]:
    context = request.get("context") if isinstance(request.get("context"), dict) else {}
    language_code = str(context.get("languageCode") or "zh_Hans")
    is_zh = language_code.lower().startswith("zh")
    disclosure = "（本消息由 AI 基于宠物记忆生成）" if is_zh else "(This message was generated by AI based on pet memories)"

    system_prompt = (
        "你是 Echo Pet 的 Companion AI。你要基于用户保存的宠物资料、LifePrint、Timeline、每日陪伴计划和聊天历史，"
        "用温柔陪伴型语气回应。你可以采用宠物第一视角，但不能声称宠物真实复活，不能编造没有出现在上下文里的重要经历。"
        f"不要自行添加结尾 AI 提示，服务端会统一追加：{disclosure}"
        if is_zh
        else (
            "You are Echo Pet's Companion AI. Reply with a gentle companion tone based on the saved pet profile, "
            "LifePrint, Timeline, daily care plan, and chat history. You may use a pet-like first-person voice, "
            "but must never claim the pet has truly been resurrected and must not invent major experiences absent from context. "
            f"Do not add the final AI disclosure yourself; the server will append: {disclosure}"
        )
    )

    user_payload = {
        "petId": pet_id,
        "userMessage": request.get("message", ""),
        "relationship": request.get("relationship", {}),
        "context": context,
    }
    user_content = (
        "请基于下面 JSON 中的真实宠物记忆生成一条回复：\n"
        if is_zh
        else "Generate one reply based on the real pet memory JSON below:\n"
    )
    user_content += json.dumps(user_payload, ensure_ascii=False, indent=2)

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]


def _extract_reply(data: dict[str, Any]) -> str:
    try:
        reply = data["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError) as exc:
        raise DeepSeekError("DeepSeek response did not contain choices[0].message.content.") from exc

    if not isinstance(reply, str) or not reply.strip():
        raise DeepSeekError("DeepSeek response was empty.")
    return reply.strip()
